name: Default Issue Template Form
description: Standard issue form.
title: "Issue title"
projects: ["mrlucciola/portfolio-page"]
assignees:
  - mrlucciola
body:
  - type: markdown
    attributes:
      value: |
        Description
