name: Push Production Build

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag Name"
        required: true
        default: "latest"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QA
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Init Bun
        uses: oven-sh/setup-bun@v1
      - name: Install deps
        run: bun install
      - name: Build prod
        run: |
          NODE_ENV=production PUBLIC_URL=https://portfolio.mrlucciola.com bun run build

      - name: Prep build files
        run: |
          git config --unset-all http.https://github.com/.extraheader
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan temp_branch
          rm .gitignore
          rm -rf node_modules
          rm tsconfig.tsbuildinfo
          git rm -rf .
          rsync -a --delete --exclude='.git/' --exclude='dist/' ./ ./
          cp -a dist/. ./
          rm -rf dist
          git add .
          git commit -m "Update prod build for ${{ steps.get_tag.outputs.TAG_NAME }}"
      - name: Push build and tag to prod repo
        run: |
          git remote remove origin
          git remote add prod git@github.com:mrlucciola/portfolio-page-prod.git
          git remote set-url prod https://x-access-token:${{ secrets.PORTFOLIO_PROD }}@github.com/mrlucciola/portfolio-page-prod.git
          git pull --rebase prod main
          git tag -f ${{ steps.get_tag.outputs.TAG_NAME }}
          git push prod temp_branch:main --force
